sqlplus SIETID/sietid@bdtramite @../drop/tables/drop-table-past.sql
sqlplus SIETID/sietid@bdtramite @../drop/tables/drop-table.sql
sqlplus SIETID/sietid@bdtramite @tables/create-tables.sql
sqlplus SIETID/sietid@bdtramite @data/00-inicial.sql
sqlplus SIETID/sietid@bdtramite @data/00-sequence.sql
sqlplus SIETID/sietid@bdtramite @data/01-ubigeo.sql
sqlplus SIETID/sietid@bdtramite @data/02-inicial-opciones.sql
sqlplus SIETID/sietid@bdtramite @data/03-inicial-dependencias.sql
sqlplus SIETID/sietid@bdtramite @data/04-inicial-paises.sql
sqlplus SIETID/sietid@bdtramite @data/05-inicial-entidades.sql
sqlplus SIETID/sietid@bdtramite @data/06-inicial-modelos.sql
sqlplus SIETID/sietid@bdtramite @data/07-inicial-delitos.sql
sqlplus SIETID/sietid@bdtramite @data/08-inicial-tipo-hecho.sql
sqlplus SIETID/sietid@bdtramite @data/09-inicial-tipo_especie.sql
sqlplus SIETID/sietid@bdtramite @data/10-inicial-organizaciones.sql