sqlplus SIETID/sietid@xe @../drop/tables/drop-table-past.sql
sqlplus SIETID/sietid@xe @../drop/tables/drop-table.sql
sqlplus SIETID/sietid@xe @tables/create-tables.sql
sqlplus SIETID/sietid@xe @data/00-inicial.sql
sqlplus SIETID/sietid@xe @data/00-sequence.sql
sqlplus SIETID/sietid@xe @data/01-ubigeo.sql
sqlplus SIETID/sietid@xe @data/02-inicial-opciones.sql
sqlplus SIETID/sietid@xe @data/03-inicial-dependencias.sql
sqlplus SIETID/sietid@xe @data/04-inicial-paises.sql
sqlplus SIETID/sietid@xe @data/05-inicial-entidades.sql
sqlplus SIETID/sietid@xe @data/06-inicial-modelos.sql
sqlplus SIETID/sietid@xe @data/07-inicial-delitos.sql
sqlplus SIETID/sietid@xe @data/08-inicial-tipo-hecho.sql
sqlplus SIETID/sietid@xe @data/09-inicial-tipo_especie.sql
sqlplus SIETID/sietid@xe @data/10-inicial-organizaciones.sql