package pe.gob.mininter.dirandro.vaadin.panel.caso;

import java.util.Iterator;
import java.util.List;

import org.apache.log4j.Logger;

import pe.gob.mininter.dirandro.model.Expediente;
import pe.gob.mininter.dirandro.model.Opcion;
import pe.gob.mininter.dirandro.util.HarecUtil;
import pe.gob.mininter.dirandro.vaadin.panel.parte.PanelRegistroParteInterviniente;
import pe.gob.mininter.dirandro.vaadin.panel.parte.PanelRegistroPartePrincipal;
import pe.gob.mininter.dirandro.vaadin.panel.parte.PanelRegistroParteVehiculo;
import pe.gob.mininter.dirandro.vaadin.util.DirandroComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TabSheet.SelectedTabChangeEvent;
import com.vaadin.ui.TabSheet.SelectedTabChangeListener;
import com.vaadin.ui.TabSheet.Tab;
import com.vaadin.ui.VerticalLayout;

public class PanelRegistroCaso extends DirandroComponent implements SelectedTabChangeListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlPrincipal;
	@AutoGenerated
	private TabSheet tabRegistroParte;
	@AutoGenerated
	private VerticalLayout tabIamgenes;
	@AutoGenerated
	private VerticalLayout tabDireccion;
	@AutoGenerated
	private VerticalLayout tabVehiculos;
	@AutoGenerated
	private PanelRegistroParteVehiculo pnlExpVehiculo;
	@AutoGenerated
	private VerticalLayout tabParticipantes;
	@AutoGenerated
	private PanelRegistroParteInterviniente panelRegistroParteInterviniente_1;
	@AutoGenerated
	private PanelRegistroPartePrincipal pnlCaso;
	private static final long serialVersionUID = -4639683924066371051L;
	private final Logger logger = Logger.getLogger(PanelRegistroCaso.class);
	
	private Expediente expediente;
	
	public PanelRegistroCaso( List<Opcion> acciones, String height ) {
		super( acciones , height );
		buildMainLayout();
		setCompositionRoot(mainLayout);
		setExpediente(new Expediente());
		postConstruct();
	}
	
	@Override
	public void postConstruct() {
		
		tabRegistroParte.addListener((SelectedTabChangeListener) this);
		//tabSheet_2.addListener((SelectedTabChangeListener) this);
//		tabSheet_3.addListener((SelectedTabChangeListener) this);
		//tabSheet_4.addListener((SelectedTabChangeListener) this);
		//tabSheet_Incautado.addListener((SelectedTabChangeListener) this);
		
		//pnlRegistroParte.setPnlAgregarDocumento(pnlAgregarDocumento);
		
		habilitarTab(false);
		tabRegistroParte.getTab(0).setEnabled(true);
	}
	
	public void habilitarTab(boolean flag) {
		Iterator<Component> i = tabRegistroParte.getComponentIterator();
		while (i.hasNext()) {
		    Component c = (Component) i.next();
		    Tab tab = tabRegistroParte.getTab(c);
		    tab.setEnabled(flag);
		}
	}
	
	@Override
	public void attach() {
		super.attach();
		
		//pnlRegistroParte.setPanelRegistroParte(this);		
		if(!expediente.esNuevo()) {
			//pnlRegistroParte.cargarFormularioExpediente();
			habilitarTab(true);
		}
	}

	@Override
	public void selectedTabChange(SelectedTabChangeEvent event) {
//		if(pnlAgregarDocumento.equals(event.getTabSheet().getSelectedTab())){
//			pnlAgregarDocumento.cargarDocumentos();
//		}
		
		if(event.getTabSheet().isEnabled()){

		
			if(pnlExpVehiculo.equals(event.getTabSheet().getSelectedTab())){
				pnlExpVehiculo.setExpediente(expediente);
			}
		
		
			
		}
	
	}
	
	public void setExpediente(Expediente expediente) {
		this.expediente = expediente;
		logger.debug("expediente = " + HarecUtil.nullToEmpty(expediente.getAutogenerado()) );
	//	pnlRegistroParte.setExpediente(expediente);
		
	}
	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlPrincipal
		pnlPrincipal = buildPnlPrincipal();
		mainLayout.addComponent(pnlPrincipal);
		mainLayout.setComponentAlignment(pnlPrincipal, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlPrincipal() {
		// common part: create layout
		pnlPrincipal = new VerticalLayout();
		pnlPrincipal.setImmediate(false);
		pnlPrincipal.setWidth("-1px");
		pnlPrincipal.setHeight("-1px");
		pnlPrincipal.setMargin(true);
		pnlPrincipal.setSpacing(true);
		
		// tabRegistroParte
		tabRegistroParte = buildTabRegistroParte();
		pnlPrincipal.addComponent(tabRegistroParte);
		pnlPrincipal.setComponentAlignment(tabRegistroParte, new Alignment(20));
		
		return pnlPrincipal;
	}

	@AutoGenerated
	private TabSheet buildTabRegistroParte() {
		// common part: create layout
		tabRegistroParte = new TabSheet();
		tabRegistroParte.setImmediate(true);
		tabRegistroParte.setWidth("950px");
		tabRegistroParte.setHeight("700px");
		
		// pnlCaso
		pnlCaso = new PanelRegistroPartePrincipal();
		pnlCaso.setImmediate(false);
		pnlCaso.setWidth("-1px");
		pnlCaso.setHeight("-1px");
		tabRegistroParte.addTab(pnlCaso, "Registrar Caso", null);
		
		// tabParticipantes
		tabParticipantes = buildTabParticipantes();
		tabRegistroParte.addTab(tabParticipantes, "Personas", null);
		
		// tabVehiculos
		tabVehiculos = buildTabVehiculos();
		tabRegistroParte.addTab(tabVehiculos, "Vehiculos", null);
		
		// tabDireccion
		tabDireccion = new VerticalLayout();
		tabDireccion.setImmediate(false);
		tabDireccion.setWidth("-1px");
		tabDireccion.setHeight("-1px");
		tabDireccion.setMargin(false);
		tabRegistroParte.addTab(tabDireccion, "Direcciones", null);
		
		// tabIamgenes
		tabIamgenes = new VerticalLayout();
		tabIamgenes.setImmediate(false);
		tabIamgenes.setWidth("-1px");
		tabIamgenes.setHeight("-1px");
		tabIamgenes.setMargin(false);
		tabRegistroParte.addTab(tabIamgenes, "Imagenes", null);
		
		return tabRegistroParte;
	}

	@AutoGenerated
	private VerticalLayout buildTabParticipantes() {
		// common part: create layout
		tabParticipantes = new VerticalLayout();
		tabParticipantes.setImmediate(false);
		tabParticipantes.setWidth("100.0%");
		tabParticipantes.setHeight("-1px");
		tabParticipantes.setMargin(false);
		
		// panelRegistroParteInterviniente_1
		panelRegistroParteInterviniente_1 = new PanelRegistroParteInterviniente();
		panelRegistroParteInterviniente_1.setImmediate(false);
		panelRegistroParteInterviniente_1.setWidth("-1px");
		panelRegistroParteInterviniente_1.setHeight("-1px");
		tabParticipantes.addComponent(panelRegistroParteInterviniente_1);
		
		return tabParticipantes;
	}

	@AutoGenerated
	private VerticalLayout buildTabVehiculos() {
		// common part: create layout
		tabVehiculos = new VerticalLayout();
		tabVehiculos.setImmediate(false);
		tabVehiculos.setWidth("100.0%");
		tabVehiculos.setHeight("-1px");
		tabVehiculos.setMargin(false);
		
		// pnlExpVehiculo
		pnlExpVehiculo = new PanelRegistroParteVehiculo();
		pnlExpVehiculo.setImmediate(false);
		pnlExpVehiculo.setWidth("100.0%");
		pnlExpVehiculo.setHeight("632px");
		tabVehiculos.addComponent(pnlExpVehiculo);
		
		return tabVehiculos;
	}

}
