package pe.gob.mininter.dirandro.vaadin.panel.informe;

import pe.gob.mininter.dirandro.model.Informe;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

@SuppressWarnings("serial")
public class PanelRegistroInformeAgenda extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlPrincipal;
	@AutoGenerated
	private Table tblAgenda;
	@AutoGenerated
	private HorizontalLayout lytFormulario3;
	@AutoGenerated
	private Button btnGuardar;
	@AutoGenerated
	private PopupDateField dtFechaVencimiento;
	@AutoGenerated
	private Label lblFechaVencimiento;
	@AutoGenerated
	private HorizontalLayout lytFormulario2;
	@AutoGenerated
	private PopupDateField dtFechaRecepcion;
	@AutoGenerated
	private Label lblFechaRecepcion;
	@AutoGenerated
	private PopupDateField dtFechaEmision;
	@AutoGenerated
	private Label lblFechaEmision;
	@AutoGenerated
	private HorizontalLayout lytFormulario1;
	@AutoGenerated
	private ComboBox cmbUnidadProcuraduria;
	@AutoGenerated
	private Label lblUnidadProcuraduria;
	@AutoGenerated
	private ComboBox cmbTipoAgenda;
	@AutoGenerated
	private Label lblTipoAgenda;
	private Informe informe;
	
	public Informe getInforme() {
		return informe;
	}

	public void setInforme(Informe informe) {
		this.informe = informe;
	}

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelRegistroInformeAgenda() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// pnlPrincipal
		pnlPrincipal = buildPnlPrincipal();
		mainLayout.addComponent(pnlPrincipal);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlPrincipal() {
		// common part: create layout
		pnlPrincipal = new VerticalLayout();
		pnlPrincipal.setImmediate(false);
		pnlPrincipal.setWidth("-1px");
		pnlPrincipal.setHeight("-1px");
		pnlPrincipal.setMargin(false);
		pnlPrincipal.setSpacing(true);
		
		// lytFormulario1
		lytFormulario1 = buildLytFormulario1();
		pnlPrincipal.addComponent(lytFormulario1);
		
		// lytFormulario2
		lytFormulario2 = buildLytFormulario2();
		pnlPrincipal.addComponent(lytFormulario2);
		
		// lytFormulario3
		lytFormulario3 = buildLytFormulario3();
		pnlPrincipal.addComponent(lytFormulario3);
		
		// tblAgenda
		tblAgenda = new Table();
		tblAgenda.setImmediate(false);
		tblAgenda.setWidth("600px");
		tblAgenda.setHeight("200px");
		pnlPrincipal.addComponent(tblAgenda);
		
		return pnlPrincipal;
	}

	@AutoGenerated
	private HorizontalLayout buildLytFormulario1() {
		// common part: create layout
		lytFormulario1 = new HorizontalLayout();
		lytFormulario1.setImmediate(false);
		lytFormulario1.setWidth("-1px");
		lytFormulario1.setHeight("-1px");
		lytFormulario1.setMargin(false);
		lytFormulario1.setSpacing(true);
		
		// lblTipoAgenda
		lblTipoAgenda = new Label();
		lblTipoAgenda.setImmediate(false);
		lblTipoAgenda.setWidth("160px");
		lblTipoAgenda.setHeight("-1px");
		lblTipoAgenda.setValue("Tipo Agenda");
		lytFormulario1.addComponent(lblTipoAgenda);
		
		// cmbTipoAgenda
		cmbTipoAgenda = new ComboBox();
		cmbTipoAgenda.setImmediate(false);
		cmbTipoAgenda.setWidth("150px");
		cmbTipoAgenda.setHeight("-1px");
		lytFormulario1.addComponent(cmbTipoAgenda);
		
		// lblUnidadProcuraduria
		lblUnidadProcuraduria = new Label();
		lblUnidadProcuraduria.setImmediate(false);
		lblUnidadProcuraduria.setWidth("160px");
		lblUnidadProcuraduria.setHeight("-1px");
		lblUnidadProcuraduria.setValue("Unidad Procuraduria");
		lytFormulario1.addComponent(lblUnidadProcuraduria);
		
		// cmbUnidadProcuraduria
		cmbUnidadProcuraduria = new ComboBox();
		cmbUnidadProcuraduria.setImmediate(false);
		cmbUnidadProcuraduria.setWidth("150px");
		cmbUnidadProcuraduria.setHeight("-1px");
		lytFormulario1.addComponent(cmbUnidadProcuraduria);
		
		return lytFormulario1;
	}

	@AutoGenerated
	private HorizontalLayout buildLytFormulario2() {
		// common part: create layout
		lytFormulario2 = new HorizontalLayout();
		lytFormulario2.setImmediate(false);
		lytFormulario2.setWidth("-1px");
		lytFormulario2.setHeight("-1px");
		lytFormulario2.setMargin(false);
		lytFormulario2.setSpacing(true);
		
		// lblFechaEmision
		lblFechaEmision = new Label();
		lblFechaEmision.setImmediate(false);
		lblFechaEmision.setWidth("160px");
		lblFechaEmision.setHeight("-1px");
		lblFechaEmision.setValue("Fecha Emision Agenda");
		lytFormulario2.addComponent(lblFechaEmision);
		
		// dtFechaEmision
		dtFechaEmision = new PopupDateField();
		dtFechaEmision.setImmediate(false);
		dtFechaEmision.setWidth("150px");
		dtFechaEmision.setHeight("-1px");
		dtFechaEmision.setResolution(4);
		lytFormulario2.addComponent(dtFechaEmision);
		
		// lblFechaRecepcion
		lblFechaRecepcion = new Label();
		lblFechaRecepcion.setImmediate(false);
		lblFechaRecepcion.setWidth("160px");
		lblFechaRecepcion.setHeight("-1px");
		lblFechaRecepcion.setValue("Fecha Recepcion Notificacion");
		lytFormulario2.addComponent(lblFechaRecepcion);
		
		// dtFechaRecepcion
		dtFechaRecepcion = new PopupDateField();
		dtFechaRecepcion.setImmediate(false);
		dtFechaRecepcion.setWidth("150px");
		dtFechaRecepcion.setHeight("-1px");
		dtFechaRecepcion.setResolution(4);
		lytFormulario2.addComponent(dtFechaRecepcion);
		
		return lytFormulario2;
	}

	@AutoGenerated
	private HorizontalLayout buildLytFormulario3() {
		// common part: create layout
		lytFormulario3 = new HorizontalLayout();
		lytFormulario3.setImmediate(false);
		lytFormulario3.setWidth("-1px");
		lytFormulario3.setHeight("-1px");
		lytFormulario3.setMargin(false);
		lytFormulario3.setSpacing(true);
		
		// lblFechaVencimiento
		lblFechaVencimiento = new Label();
		lblFechaVencimiento.setImmediate(false);
		lblFechaVencimiento.setWidth("160px");
		lblFechaVencimiento.setHeight("-1px");
		lblFechaVencimiento.setValue("Fecha Vencimiento PRI");
		lytFormulario3.addComponent(lblFechaVencimiento);
		
		// dtFechaVencimiento
		dtFechaVencimiento = new PopupDateField();
		dtFechaVencimiento.setImmediate(false);
		dtFechaVencimiento.setWidth("150px");
		dtFechaVencimiento.setHeight("-1px");
		dtFechaVencimiento.setResolution(4);
		lytFormulario3.addComponent(dtFechaVencimiento);
		
		// btnGuardar
		btnGuardar = new Button();
		btnGuardar.setCaption("Agregar");
		btnGuardar.setImmediate(false);
		btnGuardar.setWidth("-1px");
		btnGuardar.setHeight("-1px");
		lytFormulario3.addComponent(btnGuardar);
		
		return lytFormulario3;
	}

}
