package pe.gob.mininter.dirandro.vaadin.panel;

import java.util.ArrayList;
import java.util.List;

import pe.gob.mininter.dirandro.model.Correo;
import pe.gob.mininter.dirandro.model.Departamento;
import pe.gob.mininter.dirandro.model.Direccion;
import pe.gob.mininter.dirandro.model.Distrito;
import pe.gob.mininter.dirandro.model.Identificacion;
import pe.gob.mininter.dirandro.model.Opcion;
import pe.gob.mininter.dirandro.model.Parentezco;
import pe.gob.mininter.dirandro.model.Persona;
import pe.gob.mininter.dirandro.model.Provincia;
import pe.gob.mininter.dirandro.model.Valor;
import pe.gob.mininter.dirandro.vaadin.util.HarecComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Item;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.data.util.IndexedContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;

public class PanelMantenPersona extends HarecComponent implements ClickListener {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout verticalLayout_9;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_7;
	@AutoGenerated
	private Table tblImagenes;
	@AutoGenerated
	private Button button_7;
	@AutoGenerated
	private Label label_6;
	@AutoGenerated
	private VerticalLayout verticalLayout_6;
	@AutoGenerated
	private Table tblCorreos;
	@AutoGenerated
	private Button button_6;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private VerticalLayout verticalLayout_5;
	@AutoGenerated
	private Table tblDirecciones;
	@AutoGenerated
	private Button button_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private VerticalLayout verticalLayout_4;
	@AutoGenerated
	private Table tblParentescos;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Button button_8;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_8;
	@AutoGenerated
	private Button btnRegistrarPersona;
	@AutoGenerated
	private ComboBox comboBox_7;
	@AutoGenerated
	private ComboBox comboBox_6;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private HorizontalLayout pnlPersona10;
	@AutoGenerated
	private Button button_2;
	@AutoGenerated
	private Button button_1;
	@AutoGenerated
	private HorizontalLayout pnlPersona9;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private TextArea textArea_6;
	@AutoGenerated
	private TextArea textArea_7;
	@AutoGenerated
	private HorizontalLayout pnlPersona8;
	@AutoGenerated
	private TextArea textArea_5;
	@AutoGenerated
	private ComboBox comboBox_33;
	@AutoGenerated
	private ComboBox comboBox_32;
	@AutoGenerated
	private TextField textField_4;
	@AutoGenerated
	private HorizontalLayout pnlPersona7;
	@AutoGenerated
	private ComboBox comboBox_31;
	@AutoGenerated
	private ComboBox comboBox_30;
	@AutoGenerated
	private ComboBox comboBox_29;
	@AutoGenerated
	private ComboBox comboBox_28;
	@AutoGenerated
	private HorizontalLayout pnlPersona6;
	@AutoGenerated
	private ComboBox comboBox_27;
	@AutoGenerated
	private ComboBox comboBox_26;
	@AutoGenerated
	private ComboBox comboBox_25;
	@AutoGenerated
	private ComboBox comboBox_24;
	@AutoGenerated
	private HorizontalLayout pnlPersona5;
	@AutoGenerated
	private ComboBox comboBox_23;
	@AutoGenerated
	private ComboBox comboBox_22;
	@AutoGenerated
	private ComboBox comboBox_20;
	@AutoGenerated
	private ComboBox cboPiel;
	@AutoGenerated
	private HorizontalLayout pnlPersona4;
	@AutoGenerated
	private ComboBox comboBox_19;
	@AutoGenerated
	private ComboBox comboBox_18;
	@AutoGenerated
	private TextField textField_3;
	@AutoGenerated
	private TextField textField_2;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Table tblIdentificaciones;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button btnNuevo;
	@AutoGenerated
	private TextField txtNumero;
	@AutoGenerated
	private ComboBox cmbTipodoc;
	@AutoGenerated
	private VerticalLayout verticalLayout_10;
	@AutoGenerated
	private HorizontalLayout pnlPersona3;
	@AutoGenerated
	private Button btnCancelar;
	@AutoGenerated
	private Button btnGrabar;
	@AutoGenerated
	private HorizontalLayout pnlPersona2;
	@AutoGenerated
	private ComboBox cmbPersonaVerdadera;
	@AutoGenerated
	private ComboBox cmbLugarNac;
	@AutoGenerated
	private HorizontalLayout pnlPersona1;
	@AutoGenerated
	private PopupDateField dtFecNac;
	@AutoGenerated
	private ComboBox cmbSexo;
	@AutoGenerated
	private ComboBox cmbNacionalidad;
	@AutoGenerated
	private ComboBox cmbEstadoCivil;
	@AutoGenerated
	private HorizontalLayout pnlPersona;
	@AutoGenerated
	private TextField txtApeMaterno;
	@AutoGenerated
	private TextField txtApePaterno;
	@AutoGenerated
	private TextField txtNombres;
	@AutoGenerated
	private TextField txtNumDoc;
	@AutoGenerated
	private ComboBox cmbTipoDoc;
	@AutoGenerated
	private VerticalLayout verticalLayout_8;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private TextField textField_11;
	@AutoGenerated
	private TextField textField_10;
	@AutoGenerated
	private TextField textField_9;
	@AutoGenerated
	private TextField textField_8;
	@AutoGenerated
	private TextField textField_7;
	@AutoGenerated
	private TextField textField_6;
	@AutoGenerated
	private TextField textField_5;
	@AutoGenerated
	private TextField textField_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	
	PanelAgregarPersona pnlAgregarPersona;
	
	public PanelMantenPersona(List<Opcion> acciones, String height) {
		super(acciones, height);
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postConstruct();
		debugId();
	}
	
	private void debugId(){
		
	}
	
	public void postConstruct() {
		
		btnRegistrarPersona.addListener((ClickListener)this);
		
		List<Parentezco> lparentescos = null;
		Parentezco p= new Parentezco();
		Persona perPariente = new Persona();
		perPariente.setNombres("Elvis");
		perPariente.setApePaterno("Campos");
		perPariente.setApeMaterno("Mori");
		p.setId(Long.parseLong("1"));
		p.setPerPariente(perPariente);
		Valor tipoRelacion= new Valor();
		tipoRelacion.setNombre("Primo");
		p.setTipoRelacion(tipoRelacion);
		lparentescos=new ArrayList<Parentezco>();
		lparentescos.add(p);
		cargarListasParentesco(lparentescos, true);
		
		
		List<Identificacion> ldentificaciones = null;
		Identificacion i = new Identificacion();
		Persona perPersona = new Persona();
		perPersona.setNombres("Elvis");
		perPersona.setApePaterno("Mori");
		perPersona.setApeMaterno("Enriquez"); 
		i.setPerPersona(perPersona);
		i.setNumero("41563454");
		Valor tipodoc= new Valor();
		tipodoc.setNombre("DNI");
		i.setTipo(tipodoc);
		ldentificaciones=new ArrayList<Identificacion>();
		ldentificaciones.add(i);
		cargarListasIdentificacion(ldentificaciones, true);
		
		List<Direccion> ldirecciones = null;
		Direccion di = new Direccion();
		Persona ppersona = new Persona();
		ppersona.setNombres("Melissa");
		ppersona.setApePaterno("Campos");
		perPersona.setApeMaterno("Mori"); 
		di.setPerPersona(ppersona);
		di.setDireccion("Jr. Valle 234");
		di.setReferencia("A cuadra y media de Parque Sur");
		
		Distrito ubgDistrito = new Distrito();
		ubgDistrito.setNombre("San Isidro");
		Provincia ubgProvincia = new Provincia();
		ubgProvincia.setNombre("Lima");
		Departamento ubgDepartamento = new Departamento();
		ubgDepartamento.setNombre("Lima");
		ubgProvincia.setUbgDepartamento(ubgDepartamento);
		ubgDistrito.setUbgProvincia(ubgProvincia);
		di.setUbgDistrito(ubgDistrito);
		ldirecciones=new ArrayList<Direccion>();
		ldirecciones.add(di);
		cargarListasDirecciones(ldirecciones, true);
		
		
		List<Correo> lcorreos = null;
		Correo cor = new Correo();
		cor.setCorreo("mel.espinozab@gmail.com");
		lcorreos=new ArrayList<Correo>();
		lcorreos.add(cor);
		Correo cor2 = new Correo();
		cor2.setCorreo("melissae@gmail.com");
		lcorreos.add(cor2);
		cargarListasCorreos(lcorreos, true);
		
		List<Valor> contextura = null;
		Valor v= new Valor();
		v.setCodigo("1");
		v.setNombre("Delgado");
		contextura=new ArrayList<Valor>();
		contextura.add(v);
		cargarListaContextura(contextura, true);
	}
	
	@Override
	public void buttonClick(ClickEvent event) {
		if(event.getButton().equals(btnRegistrarPersona)){
			cargarWindowRegistro(1L);
		}
		
	}
	
	private void cargarWindowRegistro(Long idParte){
		pnlAgregarPersona = new PanelAgregarPersona(idParte);
		Window window=new Window(){
			
			private static final long serialVersionUID = 1L;

		      protected void close() {
		    	  getApplication().getMainWindow().removeWindow(getWindow());
		      }};
		window.setCaption("Registrar Persona");
		window.addComponent(pnlAgregarPersona);
		window.setModal(true);
		window.setResizable(false);
		window.setWidth("550px");
		window.setHeight("-1px");
		getWindow().addWindow(window);
	}
	
	private void cargarListaContextura(List<Valor> contextura, boolean flagLimpiar){
		BeanItemContainer<Valor> bicListas = new BeanItemContainer<Valor>(Valor.class,  contextura);
		System.out.println("dato "+bicListas.size());
		cboPiel.setContainerDataSource(bicListas);
		cboPiel.setItemCaptionPropertyId("nombre");
	}

	private void cargarListasCorreos(List<Correo> correos, boolean flagLimpiar){
		 IndexedContainer container = new IndexedContainer();
         container.addContainerProperty("Correo", String.class, null);
         int con=1;
         for (Correo lista: correos) {
                 Item item = container.addItem(con++);
			     item.getItemProperty("Correo").setValue(lista.getCorreo());
         }
		 tblCorreos.setContainerDataSource(container);
	}
	
	
	private void cargarListasDirecciones(List<Direccion> direcciones, boolean flagLimpiar){
		 IndexedContainer container = new IndexedContainer();
         container.addContainerProperty("Direccion", String.class, null);
         container.addContainerProperty("Referencia", String.class, null);                        
         container.addContainerProperty("Distrito", String.class, null);
         container.addContainerProperty("Provincia", String.class, null);
         container.addContainerProperty("Departamento", String.class, null);
         int con=1;
         for (Direccion lista: direcciones) {
                 Item item = container.addItem(con++);
			     item.getItemProperty("Direccion").setValue(lista.getDireccion());
			     item.getItemProperty("Referencia").setValue(lista.getReferencia());
			     item.getItemProperty("Distrito").setValue(lista.getUbgDistrito().getNombre());
			     item.getItemProperty("Provincia").setValue(lista.getUbgDistrito().getUbgProvincia().getNombre());
			     item.getItemProperty("Departamento").setValue(lista.getUbgDistrito().getUbgProvincia().getUbgDepartamento().getNombre());
         }
		
         tblDirecciones.setContainerDataSource(container);
	}
	
	
	private void cargarListasIdentificacion(List<Identificacion> identificaciones, boolean flagLimpiar)
	{
		 IndexedContainer container = new IndexedContainer();
         container.addContainerProperty("Paterno", String.class, null);
         container.addContainerProperty("Materno", String.class, null);                        
         container.addContainerProperty("Nombre", String.class, null);
         container.addContainerProperty("Tipo", String.class, null);
         container.addContainerProperty("Numero", String.class, null);
         int con=1;
         for (Identificacion lista: identificaciones) {
                 Item item = container.addItem(con++);
			     item.getItemProperty("Paterno").setValue(lista.getPerPersona().getApePaterno());
			     item.getItemProperty("Materno").setValue(lista.getPerPersona().getApeMaterno());
			     item.getItemProperty("Nombre").setValue(lista.getPerPersona().getNombres());
			     item.getItemProperty("Tipo").setValue(lista.getTipo().getNombre());
			     item.getItemProperty("Numero").setValue(lista.getNumero());
         }
		
         tblIdentificaciones.setContainerDataSource(container);
	}
	
	private void cargarListasParentesco(List<Parentezco> parentescos, boolean flagLimpiar)
	{
		 IndexedContainer container = new IndexedContainer();
         container.addContainerProperty("Paterno", String.class, null);
         container.addContainerProperty("Materno", String.class, null);                        
         container.addContainerProperty("Nombre", String.class, null);
         container.addContainerProperty("Parentesco", String.class, null);
         
         int con=1;
         for (Parentezco lista: parentescos) {
                 Item item = container.addItem(con++);
			     item.getItemProperty("Paterno").setValue(lista.getPerPariente().getApePaterno());
			     item.getItemProperty("Materno").setValue(lista.getPerPariente().getApeMaterno());
			     item.getItemProperty("Nombre").setValue(lista.getPerPariente().getNombres());
			     item.getItemProperty("Parentesco").setValue(lista.getTipoRelacion().getNombre());
         }
		
         tblParentescos.setContainerDataSource(container);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// verticalLayout_9
		verticalLayout_9 = buildVerticalLayout_9();
		mainLayout.addComponent(verticalLayout_9);
		mainLayout.setComponentAlignment(verticalLayout_9, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_9() {
		// common part: create layout
		verticalLayout_9 = new VerticalLayout();
		verticalLayout_9.setImmediate(false);
		verticalLayout_9.setWidth("-1px");
		verticalLayout_9.setHeight("-1px");
		verticalLayout_9.setMargin(true);
		
		// verticalLayout_8
		verticalLayout_8 = buildVerticalLayout_8();
		verticalLayout_9.addComponent(verticalLayout_8);
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		verticalLayout_9.addComponent(tabSheet_1);
		verticalLayout_9.setComponentAlignment(tabSheet_1, new Alignment(20));
		
		return verticalLayout_9;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_8() {
		// common part: create layout
		verticalLayout_8 = new VerticalLayout();
		verticalLayout_8.setImmediate(false);
		verticalLayout_8.setWidth("-1px");
		verticalLayout_8.setHeight("-1px");
		verticalLayout_8.setMargin(true);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		verticalLayout_8.addComponent(horizontalLayout_3);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("800px");
		table_1.setHeight("200px");
		verticalLayout_8.addComponent(table_1);
		
		return verticalLayout_8;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setImmediate(false);
		textField_1.setWidth("95px");
		textField_1.setHeight("-1px");
		textField_1.setInputPrompt("Tipo");
		horizontalLayout_3.addComponent(textField_1);
		
		// textField_5
		textField_5 = new TextField();
		textField_5.setImmediate(false);
		textField_5.setWidth("95px");
		textField_5.setHeight("-1px");
		textField_5.setInputPrompt("Documento");
		horizontalLayout_3.addComponent(textField_5);
		
		// textField_6
		textField_6 = new TextField();
		textField_6.setImmediate(false);
		textField_6.setWidth("95px");
		textField_6.setHeight("-1px");
		textField_6.setInputPrompt("Nombre");
		horizontalLayout_3.addComponent(textField_6);
		
		// textField_7
		textField_7 = new TextField();
		textField_7.setImmediate(false);
		textField_7.setWidth("95px");
		textField_7.setHeight("-1px");
		textField_7.setInputPrompt("Paterno");
		horizontalLayout_3.addComponent(textField_7);
		
		// textField_8
		textField_8 = new TextField();
		textField_8.setImmediate(false);
		textField_8.setWidth("95px");
		textField_8.setHeight("-1px");
		textField_8.setInputPrompt("Materno");
		horizontalLayout_3.addComponent(textField_8);
		
		// textField_9
		textField_9 = new TextField();
		textField_9.setImmediate(false);
		textField_9.setWidth("95px");
		textField_9.setHeight("-1px");
		textField_9.setInputPrompt("Distrito");
		horizontalLayout_3.addComponent(textField_9);
		
		// textField_10
		textField_10 = new TextField();
		textField_10.setImmediate(false);
		textField_10.setWidth("95px");
		textField_10.setHeight("-1px");
		textField_10.setInputPrompt("Nacionalidad");
		horizontalLayout_3.addComponent(textField_10);
		
		// textField_11
		textField_11 = new TextField();
		textField_11.setImmediate(false);
		textField_11.setWidth("95px");
		textField_11.setHeight("-1px");
		textField_11.setInputPrompt("Estado Civil");
		horizontalLayout_3.addComponent(textField_11);
		
		return horizontalLayout_3;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("800px");
		tabSheet_1.setHeight("320px");
		
		// verticalLayout_10
		verticalLayout_10 = buildVerticalLayout_10();
		tabSheet_1.addTab(verticalLayout_10, "Persona", null);
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		tabSheet_1.addTab(verticalLayout_2, "Identificación", null);
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		tabSheet_1.addTab(verticalLayout_3, "Detalle", null);
		
		// verticalLayout_4
		verticalLayout_4 = buildVerticalLayout_4();
		tabSheet_1.addTab(verticalLayout_4, "Parentesco", null);
		
		// verticalLayout_5
		verticalLayout_5 = buildVerticalLayout_5();
		tabSheet_1.addTab(verticalLayout_5, "Dirección", null);
		
		// verticalLayout_6
		verticalLayout_6 = buildVerticalLayout_6();
		tabSheet_1.addTab(verticalLayout_6, "Correo", null);
		
		// verticalLayout_7
		verticalLayout_7 = buildVerticalLayout_7();
		tabSheet_1.addTab(verticalLayout_7, "Imagen", null);
		
		return tabSheet_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_10() {
		// common part: create layout
		verticalLayout_10 = new VerticalLayout();
		verticalLayout_10.setImmediate(false);
		verticalLayout_10.setWidth("-1px");
		verticalLayout_10.setHeight("-1px");
		verticalLayout_10.setMargin(true);
		verticalLayout_10.setSpacing(true);
		
		// pnlPersona
		pnlPersona = buildPnlPersona();
		verticalLayout_10.addComponent(pnlPersona);
		
		// pnlPersona1
		pnlPersona1 = buildPnlPersona1();
		verticalLayout_10.addComponent(pnlPersona1);
		
		// pnlPersona2
		pnlPersona2 = buildPnlPersona2();
		verticalLayout_10.addComponent(pnlPersona2);
		
		// pnlPersona3
		pnlPersona3 = buildPnlPersona3();
		verticalLayout_10.addComponent(pnlPersona3);
		verticalLayout_10.setComponentAlignment(pnlPersona3, new Alignment(20));
		
		return verticalLayout_10;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona() {
		// common part: create layout
		pnlPersona = new HorizontalLayout();
		pnlPersona.setImmediate(false);
		pnlPersona.setWidth("-1px");
		pnlPersona.setHeight("-1px");
		pnlPersona.setMargin(false);
		pnlPersona.setSpacing(true);
		
		// cmbTipoDoc
		cmbTipoDoc = new ComboBox();
		cmbTipoDoc.setCaption("Tipo de Documento:");
		cmbTipoDoc.setImmediate(false);
		cmbTipoDoc.setWidth("-1px");
		cmbTipoDoc.setHeight("-1px");
		pnlPersona.addComponent(cmbTipoDoc);
		
		// txtNumDoc
		txtNumDoc = new TextField();
		txtNumDoc.setCaption("Numero de Documento:");
		txtNumDoc.setImmediate(false);
		txtNumDoc.setWidth("-1px");
		txtNumDoc.setHeight("-1px");
		pnlPersona.addComponent(txtNumDoc);
		
		// txtNombres
		txtNombres = new TextField();
		txtNombres.setCaption("Nombres:");
		txtNombres.setImmediate(false);
		txtNombres.setWidth("-1px");
		txtNombres.setHeight("-1px");
		pnlPersona.addComponent(txtNombres);
		
		// txtApePaterno
		txtApePaterno = new TextField();
		txtApePaterno.setCaption("Apellido Paterno:");
		txtApePaterno.setImmediate(false);
		txtApePaterno.setWidth("-1px");
		txtApePaterno.setHeight("-1px");
		pnlPersona.addComponent(txtApePaterno);
		
		// txtApeMaterno
		txtApeMaterno = new TextField();
		txtApeMaterno.setCaption("Apellido Materno:");
		txtApeMaterno.setImmediate(false);
		txtApeMaterno.setWidth("-1px");
		txtApeMaterno.setHeight("-1px");
		pnlPersona.addComponent(txtApeMaterno);
		
		return pnlPersona;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona1() {
		// common part: create layout
		pnlPersona1 = new HorizontalLayout();
		pnlPersona1.setImmediate(false);
		pnlPersona1.setWidth("-1px");
		pnlPersona1.setHeight("-1px");
		pnlPersona1.setMargin(false);
		pnlPersona1.setSpacing(true);
		
		// cmbEstadoCivil
		cmbEstadoCivil = new ComboBox();
		cmbEstadoCivil.setCaption("Estado Civil:");
		cmbEstadoCivil.setImmediate(false);
		cmbEstadoCivil.setWidth("-1px");
		cmbEstadoCivil.setHeight("-1px");
		pnlPersona1.addComponent(cmbEstadoCivil);
		
		// cmbNacionalidad
		cmbNacionalidad = new ComboBox();
		cmbNacionalidad.setCaption("Nacionalidad:");
		cmbNacionalidad.setImmediate(false);
		cmbNacionalidad.setWidth("-1px");
		cmbNacionalidad.setHeight("-1px");
		pnlPersona1.addComponent(cmbNacionalidad);
		
		// cmbSexo
		cmbSexo = new ComboBox();
		cmbSexo.setCaption("Sexo:");
		cmbSexo.setImmediate(false);
		cmbSexo.setWidth("-1px");
		cmbSexo.setHeight("-1px");
		pnlPersona1.addComponent(cmbSexo);
		
		// dtFecNac
		dtFecNac = new PopupDateField();
		dtFecNac.setCaption("Fecha de Nacimiento:");
		dtFecNac.setImmediate(false);
		dtFecNac.setWidth("-1px");
		dtFecNac.setHeight("-1px");
		pnlPersona1.addComponent(dtFecNac);
		
		return pnlPersona1;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona2() {
		// common part: create layout
		pnlPersona2 = new HorizontalLayout();
		pnlPersona2.setImmediate(false);
		pnlPersona2.setWidth("336px");
		pnlPersona2.setHeight("-1px");
		pnlPersona2.setMargin(false);
		
		// cmbLugarNac
		cmbLugarNac = new ComboBox();
		cmbLugarNac.setCaption("Lugar de Nacimiento:");
		cmbLugarNac.setImmediate(false);
		cmbLugarNac.setWidth("-1px");
		cmbLugarNac.setHeight("-1px");
		pnlPersona2.addComponent(cmbLugarNac);
		
		// cmbPersonaVerdadera
		cmbPersonaVerdadera = new ComboBox();
		cmbPersonaVerdadera.setCaption("Persona Verdadera");
		cmbPersonaVerdadera.setImmediate(false);
		cmbPersonaVerdadera.setWidth("-1px");
		cmbPersonaVerdadera.setHeight("-1px");
		pnlPersona2.addComponent(cmbPersonaVerdadera);
		
		return pnlPersona2;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona3() {
		// common part: create layout
		pnlPersona3 = new HorizontalLayout();
		pnlPersona3.setImmediate(false);
		pnlPersona3.setWidth("-1px");
		pnlPersona3.setHeight("-1px");
		pnlPersona3.setMargin(true);
		pnlPersona3.setSpacing(true);
		
		// btnGrabar
		btnGrabar = new Button();
		btnGrabar.setCaption("Grabar");
		btnGrabar.setImmediate(true);
		btnGrabar.setWidth("-1px");
		btnGrabar.setHeight("-1px");
		pnlPersona3.addComponent(btnGrabar);
		
		// btnCancelar
		btnCancelar = new Button();
		btnCancelar.setCaption("Cancelar");
		btnCancelar.setImmediate(true);
		btnCancelar.setWidth("-1px");
		btnCancelar.setHeight("-1px");
		pnlPersona3.addComponent(btnCancelar);
		
		return pnlPersona3;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("519px");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		verticalLayout_2.addComponent(horizontalLayout_2);
		
		// tblIdentificaciones
		tblIdentificaciones = new Table();
		tblIdentificaciones.setImmediate(false);
		tblIdentificaciones.setWidth("399px");
		tblIdentificaciones.setHeight("200px");
		verticalLayout_2.addComponent(tblIdentificaciones);
		
		return verticalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("381px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// cmbTipodoc
		cmbTipodoc = new ComboBox();
		cmbTipodoc.setCaption("Tipo de Documento");
		cmbTipodoc.setImmediate(false);
		cmbTipodoc.setWidth("-1px");
		cmbTipodoc.setHeight("-1px");
		cmbTipodoc.setRequired(true);
		horizontalLayout_2.addComponent(cmbTipodoc);
		
		// txtNumero
		txtNumero = new TextField();
		txtNumero.setCaption("Numero");
		txtNumero.setImmediate(false);
		txtNumero.setWidth("-1px");
		txtNumero.setHeight("-1px");
		txtNumero.setRequired(true);
		horizontalLayout_2.addComponent(txtNumero);
		
		// btnNuevo
		btnNuevo = new Button();
		btnNuevo.setCaption("Nuevo");
		btnNuevo.setImmediate(true);
		btnNuevo.setWidth("-1px");
		btnNuevo.setHeight("-1px");
		horizontalLayout_2.addComponent(btnNuevo);
		horizontalLayout_2.setComponentAlignment(btnNuevo, new Alignment(24));
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setCaption("Registrar los Rasgos de la Persona");
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("-1px");
		verticalLayout_3.setHeight("350px");
		verticalLayout_3.setMargin(true);
		verticalLayout_3.setSpacing(true);
		
		// pnlPersona4
		pnlPersona4 = buildPnlPersona4();
		verticalLayout_3.addComponent(pnlPersona4);
		
		// pnlPersona5
		pnlPersona5 = buildPnlPersona5();
		verticalLayout_3.addComponent(pnlPersona5);
		
		// pnlPersona6
		pnlPersona6 = buildPnlPersona6();
		verticalLayout_3.addComponent(pnlPersona6);
		
		// pnlPersona7
		pnlPersona7 = buildPnlPersona7();
		verticalLayout_3.addComponent(pnlPersona7);
		
		// pnlPersona8
		pnlPersona8 = buildPnlPersona8();
		verticalLayout_3.addComponent(pnlPersona8);
		
		// pnlPersona9
		pnlPersona9 = buildPnlPersona9();
		verticalLayout_3.addComponent(pnlPersona9);
		
		// pnlPersona10
		pnlPersona10 = buildPnlPersona10();
		verticalLayout_3.addComponent(pnlPersona10);
		verticalLayout_3.setComponentAlignment(pnlPersona10, new Alignment(20));
		
		return verticalLayout_3;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona4() {
		// common part: create layout
		pnlPersona4 = new HorizontalLayout();
		pnlPersona4.setImmediate(false);
		pnlPersona4.setWidth("-1px");
		pnlPersona4.setHeight("-1px");
		pnlPersona4.setMargin(false);
		pnlPersona4.setSpacing(true);
		
		// textField_2
		textField_2 = new TextField();
		textField_2.setCaption("Talla");
		textField_2.setImmediate(false);
		textField_2.setWidth("-1px");
		textField_2.setHeight("-1px");
		pnlPersona4.addComponent(textField_2);
		
		// textField_3
		textField_3 = new TextField();
		textField_3.setCaption("Peso");
		textField_3.setImmediate(false);
		textField_3.setWidth("-1px");
		textField_3.setHeight("-1px");
		pnlPersona4.addComponent(textField_3);
		
		// comboBox_18
		comboBox_18 = new ComboBox();
		comboBox_18.setCaption("Tipo ceja");
		comboBox_18.setImmediate(false);
		comboBox_18.setWidth("-1px");
		comboBox_18.setHeight("24px");
		pnlPersona4.addComponent(comboBox_18);
		
		// comboBox_19
		comboBox_19 = new ComboBox();
		comboBox_19.setCaption("Tipo oreja");
		comboBox_19.setImmediate(false);
		comboBox_19.setWidth("-1px");
		comboBox_19.setHeight("-1px");
		pnlPersona4.addComponent(comboBox_19);
		
		return pnlPersona4;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona5() {
		// common part: create layout
		pnlPersona5 = new HorizontalLayout();
		pnlPersona5.setImmediate(false);
		pnlPersona5.setWidth("-1px");
		pnlPersona5.setHeight("-1px");
		pnlPersona5.setMargin(false);
		pnlPersona5.setSpacing(true);
		
		// cboPiel
		cboPiel = new ComboBox();
		cboPiel.setCaption("Color piel");
		cboPiel.setImmediate(false);
		cboPiel.setWidth("-1px");
		cboPiel.setHeight("-1px");
		pnlPersona5.addComponent(cboPiel);
		
		// comboBox_20
		comboBox_20 = new ComboBox();
		comboBox_20.setCaption("Contextura");
		comboBox_20.setImmediate(false);
		comboBox_20.setWidth("-1px");
		comboBox_20.setHeight("-1px");
		pnlPersona5.addComponent(comboBox_20);
		
		// comboBox_22
		comboBox_22 = new ComboBox();
		comboBox_22.setCaption("Tipo cabello");
		comboBox_22.setImmediate(false);
		comboBox_22.setWidth("-1px");
		comboBox_22.setHeight("-1px");
		pnlPersona5.addComponent(comboBox_22);
		
		// comboBox_23
		comboBox_23 = new ComboBox();
		comboBox_23.setCaption("Tipo raza");
		comboBox_23.setImmediate(false);
		comboBox_23.setWidth("-1px");
		comboBox_23.setHeight("-1px");
		pnlPersona5.addComponent(comboBox_23);
		
		return pnlPersona5;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona6() {
		// common part: create layout
		pnlPersona6 = new HorizontalLayout();
		pnlPersona6.setImmediate(false);
		pnlPersona6.setWidth("-1px");
		pnlPersona6.setHeight("-1px");
		pnlPersona6.setMargin(false);
		pnlPersona6.setSpacing(true);
		
		// comboBox_24
		comboBox_24 = new ComboBox();
		comboBox_24.setCaption("Color cabello");
		comboBox_24.setImmediate(false);
		comboBox_24.setWidth("-1px");
		comboBox_24.setHeight("-1px");
		pnlPersona6.addComponent(comboBox_24);
		
		// comboBox_25
		comboBox_25 = new ComboBox();
		comboBox_25.setCaption("Corte cabello");
		comboBox_25.setImmediate(false);
		comboBox_25.setWidth("-1px");
		comboBox_25.setHeight("-1px");
		pnlPersona6.addComponent(comboBox_25);
		
		// comboBox_26
		comboBox_26 = new ComboBox();
		comboBox_26.setCaption("Tipo ojo");
		comboBox_26.setImmediate(false);
		comboBox_26.setWidth("-1px");
		comboBox_26.setHeight("-1px");
		pnlPersona6.addComponent(comboBox_26);
		
		// comboBox_27
		comboBox_27 = new ComboBox();
		comboBox_27.setCaption("Color ojo");
		comboBox_27.setImmediate(false);
		comboBox_27.setWidth("-1px");
		comboBox_27.setHeight("-1px");
		pnlPersona6.addComponent(comboBox_27);
		
		return pnlPersona6;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona7() {
		// common part: create layout
		pnlPersona7 = new HorizontalLayout();
		pnlPersona7.setImmediate(false);
		pnlPersona7.setWidth("-1px");
		pnlPersona7.setHeight("-1px");
		pnlPersona7.setMargin(false);
		pnlPersona7.setSpacing(true);
		
		// comboBox_28
		comboBox_28 = new ComboBox();
		comboBox_28.setCaption("Tipo nariz");
		comboBox_28.setImmediate(false);
		comboBox_28.setWidth("-1px");
		comboBox_28.setHeight("-1px");
		pnlPersona7.addComponent(comboBox_28);
		
		// comboBox_29
		comboBox_29 = new ComboBox();
		comboBox_29.setCaption("Forma cara");
		comboBox_29.setImmediate(false);
		comboBox_29.setWidth("-1px");
		comboBox_29.setHeight("-1px");
		pnlPersona7.addComponent(comboBox_29);
		
		// comboBox_30
		comboBox_30 = new ComboBox();
		comboBox_30.setCaption("Tipo labio");
		comboBox_30.setImmediate(false);
		comboBox_30.setWidth("-1px");
		comboBox_30.setHeight("-1px");
		pnlPersona7.addComponent(comboBox_30);
		
		// comboBox_31
		comboBox_31 = new ComboBox();
		comboBox_31.setCaption("Forma boca");
		comboBox_31.setImmediate(false);
		comboBox_31.setWidth("-1px");
		comboBox_31.setHeight("-1px");
		pnlPersona7.addComponent(comboBox_31);
		
		return pnlPersona7;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona8() {
		// common part: create layout
		pnlPersona8 = new HorizontalLayout();
		pnlPersona8.setImmediate(false);
		pnlPersona8.setWidth("-1px");
		pnlPersona8.setHeight("-1px");
		pnlPersona8.setMargin(false);
		pnlPersona8.setSpacing(true);
		
		// textField_4
		textField_4 = new TextField();
		textField_4.setCaption("Calzado");
		textField_4.setImmediate(false);
		textField_4.setWidth("-1px");
		textField_4.setHeight("-1px");
		pnlPersona8.addComponent(textField_4);
		
		// comboBox_32
		comboBox_32 = new ComboBox();
		comboBox_32.setCaption("Corte de cabello");
		comboBox_32.setImmediate(false);
		comboBox_32.setWidth("-1px");
		comboBox_32.setHeight("-1px");
		pnlPersona8.addComponent(comboBox_32);
		
		// comboBox_33
		comboBox_33 = new ComboBox();
		comboBox_33.setCaption("Profesión");
		comboBox_33.setImmediate(false);
		comboBox_33.setWidth("-1px");
		comboBox_33.setHeight("-1px");
		pnlPersona8.addComponent(comboBox_33);
		
		// textArea_5
		textArea_5 = new TextArea();
		textArea_5.setCaption("Señas");
		textArea_5.setImmediate(false);
		textArea_5.setWidth("153px");
		textArea_5.setHeight("34px");
		pnlPersona8.addComponent(textArea_5);
		
		return pnlPersona8;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona9() {
		// common part: create layout
		pnlPersona9 = new HorizontalLayout();
		pnlPersona9.setImmediate(false);
		pnlPersona9.setWidth("-1px");
		pnlPersona9.setHeight("-1px");
		pnlPersona9.setMargin(false);
		pnlPersona9.setSpacing(true);
		
		// textArea_7
		textArea_7 = new TextArea();
		textArea_7.setCaption("Vestimenta");
		textArea_7.setImmediate(false);
		textArea_7.setWidth("200px");
		textArea_7.setHeight("50px");
		pnlPersona9.addComponent(textArea_7);
		
		// textArea_6
		textArea_6 = new TextArea();
		textArea_6.setCaption("Razgo facial");
		textArea_6.setImmediate(false);
		textArea_6.setWidth("200px");
		textArea_6.setHeight("50px");
		pnlPersona9.addComponent(textArea_6);
		
		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setCaption("Ult. vez visto");
		textArea_1.setImmediate(false);
		textArea_1.setWidth("200px");
		textArea_1.setHeight("50px");
		pnlPersona9.addComponent(textArea_1);
		
		return pnlPersona9;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPersona10() {
		// common part: create layout
		pnlPersona10 = new HorizontalLayout();
		pnlPersona10.setImmediate(false);
		pnlPersona10.setWidth("-1px");
		pnlPersona10.setHeight("-1px");
		pnlPersona10.setMargin(true);
		pnlPersona10.setSpacing(true);
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Grabar");
		button_1.setImmediate(true);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		pnlPersona10.addComponent(button_1);
		
		// button_2
		button_2 = new Button();
		button_2.setCaption("Cancelar");
		button_2.setImmediate(true);
		button_2.setWidth("-1px");
		button_2.setHeight("-1px");
		pnlPersona10.addComponent(button_2);
		
		return pnlPersona10;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_4() {
		// common part: create layout
		verticalLayout_4 = new VerticalLayout();
		verticalLayout_4.setImmediate(false);
		verticalLayout_4.setWidth("-1px");
		verticalLayout_4.setHeight("-1px");
		verticalLayout_4.setMargin(true);
		verticalLayout_4.setSpacing(true);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		verticalLayout_4.addComponent(horizontalLayout_1);
		
		// tblParentescos
		tblParentescos = new Table();
		tblParentescos.setImmediate(false);
		tblParentescos.setWidth("700px");
		tblParentescos.setHeight("200px");
		verticalLayout_4.addComponent(tblParentescos);
		
		return verticalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("100.0%");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// horizontalLayout_8
		horizontalLayout_8 = buildHorizontalLayout_8();
		horizontalLayout_1.addComponent(horizontalLayout_8);
		
		// button_8
		button_8 = new Button();
		button_8.setCaption("Agregar Pariente");
		button_8.setImmediate(true);
		button_8.setWidth("-1px");
		button_8.setHeight("-1px");
		horizontalLayout_1.addComponent(button_8);
		horizontalLayout_1.setComponentAlignment(button_8, new Alignment(10));
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_8() {
		// common part: create layout
		horizontalLayout_8 = new HorizontalLayout();
		horizontalLayout_8.setImmediate(false);
		horizontalLayout_8.setWidth("-1px");
		horizontalLayout_8.setHeight("-1px");
		horizontalLayout_8.setMargin(false);
		horizontalLayout_8.setSpacing(true);
		
		// comboBox_6
		comboBox_6 = new ComboBox();
		comboBox_6.setCaption("Tipo de Parentezco:");
		comboBox_6.setImmediate(false);
		comboBox_6.setWidth("-1px");
		comboBox_6.setHeight("-1px");
		horizontalLayout_8.addComponent(comboBox_6);
		
		// comboBox_7
		comboBox_7 = new ComboBox();
		comboBox_7.setCaption("Persona Pariente:");
		comboBox_7.setImmediate(false);
		comboBox_7.setWidth("300px");
		comboBox_7.setHeight("-1px");
		horizontalLayout_8.addComponent(comboBox_7);
		
		// btnRegistrarPersona
		btnRegistrarPersona = new Button();
		btnRegistrarPersona.setCaption("Nuevo");
		btnRegistrarPersona.setImmediate(true);
		btnRegistrarPersona.setWidth("-1px");
		btnRegistrarPersona.setHeight("-1px");
		horizontalLayout_8.addComponent(btnRegistrarPersona);
		horizontalLayout_8.setComponentAlignment(btnRegistrarPersona,
				new Alignment(9));
		
		return horizontalLayout_8;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_5() {
		// common part: create layout
		verticalLayout_5 = new VerticalLayout();
		verticalLayout_5.setImmediate(false);
		verticalLayout_5.setWidth("100.22%");
		verticalLayout_5.setHeight("94.8%");
		verticalLayout_5.setMargin(false);
		
		// label_4
		label_4 = new Label();
		label_4.setImmediate(false);
		label_4.setWidth("190px");
		label_4.setHeight("-1px");
		label_4.setValue("Lista de Direcciones");
		verticalLayout_5.addComponent(label_4);
		
		// button_5
		button_5 = new Button();
		button_5.setCaption("Agregar");
		button_5.setImmediate(true);
		button_5.setWidth("-1px");
		button_5.setHeight("-1px");
		verticalLayout_5.addComponent(button_5);
		
		// tblDirecciones
		tblDirecciones = new Table();
		tblDirecciones.setImmediate(false);
		tblDirecciones.setWidth("-1px");
		tblDirecciones.setHeight("-1px");
		verticalLayout_5.addComponent(tblDirecciones);
		
		return verticalLayout_5;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_6() {
		// common part: create layout
		verticalLayout_6 = new VerticalLayout();
		verticalLayout_6.setImmediate(false);
		verticalLayout_6.setWidth("100.0%");
		verticalLayout_6.setHeight("100.0%");
		verticalLayout_6.setMargin(false);
		
		// label_5
		label_5 = new Label();
		label_5.setImmediate(false);
		label_5.setWidth("319px");
		label_5.setHeight("-1px");
		label_5.setValue("Lista de correos");
		verticalLayout_6.addComponent(label_5);
		
		// button_6
		button_6 = new Button();
		button_6.setCaption("Agregar");
		button_6.setImmediate(true);
		button_6.setWidth("-1px");
		button_6.setHeight("-1px");
		verticalLayout_6.addComponent(button_6);
		
		// tblCorreos
		tblCorreos = new Table();
		tblCorreos.setImmediate(false);
		tblCorreos.setWidth("-1px");
		tblCorreos.setHeight("-1px");
		verticalLayout_6.addComponent(tblCorreos);
		
		return verticalLayout_6;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_7() {
		// common part: create layout
		verticalLayout_7 = new VerticalLayout();
		verticalLayout_7.setImmediate(false);
		verticalLayout_7.setWidth("100.0%");
		verticalLayout_7.setHeight("100.0%");
		verticalLayout_7.setMargin(false);
		
		// label_6
		label_6 = new Label();
		label_6.setImmediate(false);
		label_6.setWidth("179px");
		label_6.setHeight("-1px");
		label_6.setValue("Lista de imágenes");
		verticalLayout_7.addComponent(label_6);
		
		// button_7
		button_7 = new Button();
		button_7.setCaption("Agregar");
		button_7.setImmediate(true);
		button_7.setWidth("-1px");
		button_7.setHeight("-1px");
		verticalLayout_7.addComponent(button_7);
		
		// tblImagenes
		tblImagenes = new Table();
		tblImagenes.setImmediate(false);
		tblImagenes.setWidth("-1px");
		tblImagenes.setHeight("-1px");
		verticalLayout_7.addComponent(tblImagenes);
		
		return verticalLayout_7;
	}

}
