package pe.gob.mininter.dirandro.vaadin.panel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PanelRegistroParteNoIdentificado extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlPrincipal1;
	@AutoGenerated
	private Table tblNoIdentidifacos;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private Button btnPNIGrabar;
	@AutoGenerated
	private TextField txtPNIEdad;
	@AutoGenerated
	private ComboBox cmbPNIOrientacionSexual;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField txtPNIApellidos;
	@AutoGenerated
	private TextField txtPNINombres;
	@AutoGenerated
	private TextField txtPNIAlias;
	private static final long serialVersionUID = -4639683924066371051L;
	
	
	public PanelRegistroParteNoIdentificado() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postConstruct();
	}
	
	public void postConstruct() {
		
	}
	
	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlPrincipal1
		pnlPrincipal1 = buildPnlPrincipal1();
		mainLayout.addComponent(pnlPrincipal1);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlPrincipal1() {
		// common part: create layout
		pnlPrincipal1 = new VerticalLayout();
		pnlPrincipal1.setImmediate(false);
		pnlPrincipal1.setWidth("-1px");
		pnlPrincipal1.setHeight("-1px");
		pnlPrincipal1.setMargin(false);
		pnlPrincipal1.setSpacing(true);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		pnlPrincipal1.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		pnlPrincipal1.addComponent(horizontalLayout_2);
		
		// tblNoIdentidifacos
		tblNoIdentidifacos = new Table();
		tblNoIdentidifacos.setImmediate(false);
		tblNoIdentidifacos.setWidth("870px");
		tblNoIdentidifacos.setHeight("-1px");
		pnlPrincipal1.addComponent(tblNoIdentidifacos);
		
		return pnlPrincipal1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// txtPNIAlias
		txtPNIAlias = new TextField();
		txtPNIAlias.setCaption("Alias");
		txtPNIAlias.setImmediate(false);
		txtPNIAlias.setWidth("250px");
		txtPNIAlias.setHeight("-1px");
		txtPNIAlias.setRequired(true);
		txtPNIAlias.setInputPrompt("Alias del presunto implicado");
		horizontalLayout_1.addComponent(txtPNIAlias);
		
		// txtPNINombres
		txtPNINombres = new TextField();
		txtPNINombres.setCaption("Nombres");
		txtPNINombres.setImmediate(false);
		txtPNINombres.setWidth("250px");
		txtPNINombres.setHeight("-1px");
		txtPNINombres.setInputPrompt("Presuntos nombres del detenido");
		horizontalLayout_1.addComponent(txtPNINombres);
		
		// txtPNIApellidos
		txtPNIApellidos = new TextField();
		txtPNIApellidos.setCaption("Apellidos");
		txtPNIApellidos.setImmediate(false);
		txtPNIApellidos.setWidth("250px");
		txtPNIApellidos.setHeight("-1px");
		txtPNIApellidos.setInputPrompt("Presuntos Apellidos del detenido");
		horizontalLayout_1.addComponent(txtPNIApellidos);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// cmbPNIOrientacionSexual
		cmbPNIOrientacionSexual = new ComboBox();
		cmbPNIOrientacionSexual.setCaption("Orientacion Sexual");
		cmbPNIOrientacionSexual.setImmediate(false);
		cmbPNIOrientacionSexual.setWidth("-1px");
		cmbPNIOrientacionSexual.setHeight("-1px");
		horizontalLayout_2.addComponent(cmbPNIOrientacionSexual);
		
		// txtPNIEdad
		txtPNIEdad = new TextField();
		txtPNIEdad.setCaption("Edad Aproximada");
		txtPNIEdad.setImmediate(false);
		txtPNIEdad.setWidth("-1px");
		txtPNIEdad.setHeight("-1px");
		txtPNIEdad.setInputPrompt("Edad Aproximada");
		horizontalLayout_2.addComponent(txtPNIEdad);
		
		// btnPNIGrabar
		btnPNIGrabar = new Button();
		btnPNIGrabar.setCaption("Grabar");
		btnPNIGrabar.setImmediate(true);
		btnPNIGrabar.setWidth("-1px");
		btnPNIGrabar.setHeight("-1px");
		horizontalLayout_2.addComponent(btnPNIGrabar);
		horizontalLayout_2.setComponentAlignment(btnPNIGrabar,
				new Alignment(10));
		
		return horizontalLayout_2;
	}

}
