package pe.gob.mininter.dirandro.vaadin.panel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PanelAbogadoPersona extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlPrincipal;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_3;
	@AutoGenerated
	private Table table_2;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_5;
	@AutoGenerated
	private ComboBox cmbEstado;
	@AutoGenerated
	private PopupDateField dtFechaIniRep;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_2;
	@AutoGenerated
	private TextField txtLugarNac;
	@AutoGenerated
	private TextField txtSexo;
	@AutoGenerated
	private TextField txtNacionalidad;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private TextField txtNroDocumento;
	@AutoGenerated
	private TextField textField_1;
	@AutoGenerated
	private TextField txtTipoDoc;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_4;
	@AutoGenerated
	private Button btnLetrado;
	@AutoGenerated
	private Button btnRegistrar;
	@AutoGenerated
	private TextField txtAbogado;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public PanelAbogadoPersona() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlPrincipal
		pnlPrincipal = buildPnlPrincipal();
		mainLayout.addComponent(pnlPrincipal);
		mainLayout.setComponentAlignment(pnlPrincipal, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlPrincipal() {
		// common part: create layout
		pnlPrincipal = new VerticalLayout();
		pnlPrincipal.setImmediate(false);
		pnlPrincipal.setWidth("-1px");
		pnlPrincipal.setHeight("300px");
		pnlPrincipal.setMargin(true);
		pnlPrincipal.setSpacing(true);
		
		// label_1
		label_1 = new Label();
		label_1.setStyleName("h2");
		label_1.setImmediate(false);
		label_1.setWidth("304px");
		label_1.setHeight("-1px");
		label_1.setValue("Abogados que representan al Implicado");
		pnlPrincipal.addComponent(label_1);
		pnlPrincipal.setComponentAlignment(label_1, new Alignment(20));
		
		// horizontalLayout_4
		horizontalLayout_4 = buildHorizontalLayout_4();
		pnlPrincipal.addComponent(horizontalLayout_4);
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		pnlPrincipal.addComponent(horizontalLayout_1);
		
		// horizontalLayout_2
		horizontalLayout_2 = buildHorizontalLayout_2();
		pnlPrincipal.addComponent(horizontalLayout_2);
		
		// horizontalLayout_5
		horizontalLayout_5 = buildHorizontalLayout_5();
		pnlPrincipal.addComponent(horizontalLayout_5);
		
		// horizontalLayout_3
		horizontalLayout_3 = buildHorizontalLayout_3();
		pnlPrincipal.addComponent(horizontalLayout_3);
		
		return pnlPrincipal;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_4() {
		// common part: create layout
		horizontalLayout_4 = new HorizontalLayout();
		horizontalLayout_4.setImmediate(false);
		horizontalLayout_4.setWidth("-1px");
		horizontalLayout_4.setHeight("-1px");
		horizontalLayout_4.setMargin(false);
		horizontalLayout_4.setSpacing(true);
		
		// txtAbogado
		txtAbogado = new TextField();
		txtAbogado.setCaption("Abogado");
		txtAbogado.setImmediate(false);
		txtAbogado.setWidth("-1px");
		txtAbogado.setHeight("-1px");
		horizontalLayout_4.addComponent(txtAbogado);
		
		// btnRegistrar
		btnRegistrar = new Button();
		btnRegistrar.setCaption("Registrar");
		btnRegistrar.setImmediate(true);
		btnRegistrar.setWidth("-1px");
		btnRegistrar.setHeight("-1px");
		horizontalLayout_4.addComponent(btnRegistrar);
		horizontalLayout_4
				.setComponentAlignment(btnRegistrar, new Alignment(9));
		
		// btnLetrado
		btnLetrado = new Button();
		btnLetrado.setCaption("Agregar Letrado");
		btnLetrado.setImmediate(true);
		btnLetrado.setWidth("-1px");
		btnLetrado.setHeight("-1px");
		horizontalLayout_4.addComponent(btnLetrado);
		horizontalLayout_4.setComponentAlignment(btnLetrado, new Alignment(9));
		
		return horizontalLayout_4;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		horizontalLayout_1.setSpacing(true);
		
		// txtTipoDoc
		txtTipoDoc = new TextField();
		txtTipoDoc.setCaption("Tipo de documento");
		txtTipoDoc.setImmediate(false);
		txtTipoDoc.setWidth("-1px");
		txtTipoDoc.setHeight("-1px");
		horizontalLayout_1.addComponent(txtTipoDoc);
		
		// textField_1
		textField_1 = new TextField();
		textField_1.setCaption("Nro. de documento");
		textField_1.setImmediate(false);
		textField_1.setWidth("-1px");
		textField_1.setHeight("-1px");
		horizontalLayout_1.addComponent(textField_1);
		
		// txtNroDocumento
		txtNroDocumento = new TextField();
		txtNroDocumento.setCaption("Nombre completo");
		txtNroDocumento.setImmediate(false);
		txtNroDocumento.setWidth("-1px");
		txtNroDocumento.setHeight("-1px");
		horizontalLayout_1.addComponent(txtNroDocumento);
		
		return horizontalLayout_1;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_2() {
		// common part: create layout
		horizontalLayout_2 = new HorizontalLayout();
		horizontalLayout_2.setImmediate(false);
		horizontalLayout_2.setWidth("-1px");
		horizontalLayout_2.setHeight("-1px");
		horizontalLayout_2.setMargin(false);
		horizontalLayout_2.setSpacing(true);
		
		// txtNacionalidad
		txtNacionalidad = new TextField();
		txtNacionalidad.setCaption("Nacionalidad");
		txtNacionalidad.setImmediate(false);
		txtNacionalidad.setWidth("-1px");
		txtNacionalidad.setHeight("-1px");
		horizontalLayout_2.addComponent(txtNacionalidad);
		
		// txtSexo
		txtSexo = new TextField();
		txtSexo.setCaption("Sexo");
		txtSexo.setImmediate(false);
		txtSexo.setWidth("-1px");
		txtSexo.setHeight("-1px");
		horizontalLayout_2.addComponent(txtSexo);
		
		// txtLugarNac
		txtLugarNac = new TextField();
		txtLugarNac.setCaption("Lugar de Nacimiento");
		txtLugarNac.setImmediate(false);
		txtLugarNac.setWidth("-1px");
		txtLugarNac.setHeight("-1px");
		horizontalLayout_2.addComponent(txtLugarNac);
		
		return horizontalLayout_2;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_5() {
		// common part: create layout
		horizontalLayout_5 = new HorizontalLayout();
		horizontalLayout_5.setImmediate(false);
		horizontalLayout_5.setWidth("-1px");
		horizontalLayout_5.setHeight("-1px");
		horizontalLayout_5.setMargin(false);
		horizontalLayout_5.setSpacing(true);
		
		// dtFechaIniRep
		dtFechaIniRep = new PopupDateField();
		dtFechaIniRep.setCaption("Fecha inicio de representación");
		dtFechaIniRep.setImmediate(false);
		dtFechaIniRep.setWidth("-1px");
		dtFechaIniRep.setHeight("-1px");
		horizontalLayout_5.addComponent(dtFechaIniRep);
		
		// cmbEstado
		cmbEstado = new ComboBox();
		cmbEstado.setCaption("Estado");
		cmbEstado.setImmediate(false);
		cmbEstado.setWidth("-1px");
		cmbEstado.setHeight("-1px");
		horizontalLayout_5.addComponent(cmbEstado);
		
		return horizontalLayout_5;
	}

	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_3() {
		// common part: create layout
		horizontalLayout_3 = new HorizontalLayout();
		horizontalLayout_3.setImmediate(false);
		horizontalLayout_3.setWidth("-1px");
		horizontalLayout_3.setHeight("-1px");
		horizontalLayout_3.setMargin(false);
		horizontalLayout_3.setSpacing(true);
		
		// table_2
		table_2 = new Table();
		table_2.setImmediate(false);
		table_2.setWidth("680px");
		table_2.setHeight("-1px");
		horizontalLayout_3.addComponent(table_2);
		
		return horizontalLayout_3;
	}

}
