package pe.gob.mininter.dirandro.vaadin.panel;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class PanelRegistroParteEspecie extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private VerticalLayout pnlPrincipalEspecie;
	@AutoGenerated
	private Table tblEspListaEspecies;
	@AutoGenerated
	private HorizontalLayout pnlEspecie3;
	@AutoGenerated
	private Button btnEspAgregar;
	@AutoGenerated
	private ComboBox cmbEspEstado;
	@AutoGenerated
	private ComboBox cmbEspSituacion;
	@AutoGenerated
	private HorizontalLayout pnlEspecie2;
	@AutoGenerated
	private TextField txtEspNumeroSerie;
	@AutoGenerated
	private TextField txtEspMedida;
	@AutoGenerated
	private ComboBox cmbEspTipoMedida;
	@AutoGenerated
	private TextField txtEspNombre;
	@AutoGenerated
	private HorizontalLayout pnlEspecie1;
	@AutoGenerated
	private ComboBox cmbEspTipo;
	@AutoGenerated
	private ComboBox cmbEspFamilia;
	private static final long serialVersionUID = -5843290610457087118L;
	
	public PanelRegistroParteEspecie() {
		super();
		buildMainLayout();
		setCompositionRoot(mainLayout);
		postConstruct();
	}

	public void postConstruct() {
		
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlPrincipalEspecie
		pnlPrincipalEspecie = buildPnlPrincipalEspecie();
		mainLayout.addComponent(pnlPrincipalEspecie);
		
		return mainLayout;
	}

	@AutoGenerated
	private VerticalLayout buildPnlPrincipalEspecie() {
		// common part: create layout
		pnlPrincipalEspecie = new VerticalLayout();
		pnlPrincipalEspecie.setImmediate(false);
		pnlPrincipalEspecie.setWidth("-1px");
		pnlPrincipalEspecie.setHeight("-1px");
		pnlPrincipalEspecie.setMargin(true);
		pnlPrincipalEspecie.setSpacing(true);
		
		// pnlEspecie1
		pnlEspecie1 = buildPnlEspecie1();
		pnlPrincipalEspecie.addComponent(pnlEspecie1);
		
		// pnlEspecie2
		pnlEspecie2 = buildPnlEspecie2();
		pnlPrincipalEspecie.addComponent(pnlEspecie2);
		
		// pnlEspecie3
		pnlEspecie3 = buildPnlEspecie3();
		pnlPrincipalEspecie.addComponent(pnlEspecie3);
		
		// tblEspListaEspecies
		tblEspListaEspecies = new Table();
		tblEspListaEspecies.setImmediate(false);
		tblEspListaEspecies.setWidth("800px");
		tblEspListaEspecies.setHeight("250px");
		pnlPrincipalEspecie.addComponent(tblEspListaEspecies);
		
		return pnlPrincipalEspecie;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlEspecie1() {
		// common part: create layout
		pnlEspecie1 = new HorizontalLayout();
		pnlEspecie1.setImmediate(false);
		pnlEspecie1.setWidth("-1px");
		pnlEspecie1.setHeight("-1px");
		pnlEspecie1.setMargin(false);
		pnlEspecie1.setSpacing(true);
		
		// cmbEspFamilia
		cmbEspFamilia = new ComboBox();
		cmbEspFamilia.setCaption("Familia de Especie");
		cmbEspFamilia.setImmediate(false);
		cmbEspFamilia.setWidth("-1px");
		cmbEspFamilia.setHeight("-1px");
		pnlEspecie1.addComponent(cmbEspFamilia);
		
		// cmbEspTipo
		cmbEspTipo = new ComboBox();
		cmbEspTipo.setCaption("Tipo de Especie");
		cmbEspTipo.setImmediate(false);
		cmbEspTipo.setWidth("-1px");
		cmbEspTipo.setHeight("-1px");
		pnlEspecie1.addComponent(cmbEspTipo);
		
		return pnlEspecie1;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlEspecie2() {
		// common part: create layout
		pnlEspecie2 = new HorizontalLayout();
		pnlEspecie2.setImmediate(false);
		pnlEspecie2.setWidth("-1px");
		pnlEspecie2.setHeight("-1px");
		pnlEspecie2.setMargin(false);
		pnlEspecie2.setSpacing(true);
		
		// txtEspNombre
		txtEspNombre = new TextField();
		txtEspNombre.setCaption("Nombre");
		txtEspNombre.setImmediate(false);
		txtEspNombre.setWidth("130px");
		txtEspNombre.setHeight("-1px");
		txtEspNombre.setRequired(true);
		txtEspNombre.setInputPrompt("Nombre");
		txtEspNombre.setMaxLength(50);
		pnlEspecie2.addComponent(txtEspNombre);
		
		// cmbEspTipoMedida
		cmbEspTipoMedida = new ComboBox();
		cmbEspTipoMedida.setCaption("Tipo Medida");
		cmbEspTipoMedida.setImmediate(false);
		cmbEspTipoMedida.setWidth("-1px");
		cmbEspTipoMedida.setHeight("-1px");
		cmbEspTipoMedida.setRequired(true);
		pnlEspecie2.addComponent(cmbEspTipoMedida);
		
		// txtEspMedida
		txtEspMedida = new TextField();
		txtEspMedida.setCaption("Medida");
		txtEspMedida.setImmediate(false);
		txtEspMedida.setWidth("80px");
		txtEspMedida.setHeight("-1px");
		txtEspMedida.setRequired(true);
		txtEspMedida.setInputPrompt("Medida");
		txtEspMedida.setMaxLength(50);
		pnlEspecie2.addComponent(txtEspMedida);
		
		// txtEspNumeroSerie
		txtEspNumeroSerie = new TextField();
		txtEspNumeroSerie.setCaption("Número de Serie");
		txtEspNumeroSerie.setImmediate(false);
		txtEspNumeroSerie.setWidth("200px");
		txtEspNumeroSerie.setHeight("-1px");
		txtEspNumeroSerie.setInputPrompt("Número de Serie de la especie");
		pnlEspecie2.addComponent(txtEspNumeroSerie);
		
		return pnlEspecie2;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlEspecie3() {
		// common part: create layout
		pnlEspecie3 = new HorizontalLayout();
		pnlEspecie3.setImmediate(false);
		pnlEspecie3.setWidth("-1px");
		pnlEspecie3.setHeight("-1px");
		pnlEspecie3.setMargin(false);
		pnlEspecie3.setSpacing(true);
		
		// cmbEspSituacion
		cmbEspSituacion = new ComboBox();
		cmbEspSituacion.setCaption("Situación");
		cmbEspSituacion.setImmediate(false);
		cmbEspSituacion.setWidth("-1px");
		cmbEspSituacion.setHeight("-1px");
		cmbEspSituacion.setRequired(true);
		pnlEspecie3.addComponent(cmbEspSituacion);
		
		// cmbEspEstado
		cmbEspEstado = new ComboBox();
		cmbEspEstado.setCaption("Estado");
		cmbEspEstado.setImmediate(false);
		cmbEspEstado.setWidth("-1px");
		cmbEspEstado.setHeight("-1px");
		cmbEspEstado.setRequired(true);
		pnlEspecie3.addComponent(cmbEspEstado);
		
		// btnEspAgregar
		btnEspAgregar = new Button();
		btnEspAgregar.setCaption("Agregar Especie");
		btnEspAgregar.setImmediate(true);
		btnEspAgregar.setWidth("-1px");
		btnEspAgregar.setHeight("-1px");
		pnlEspecie3.addComponent(btnEspAgregar);
		pnlEspecie3.setComponentAlignment(btnEspAgregar, new Alignment(24));
		
		return pnlEspecie3;
	}

}
