package pe.gob.mininter.dirandro.vaadin.panel;

import java.util.List;

import pe.gob.mininter.dirandro.model.Opcion;
import pe.gob.mininter.dirandro.service.EstadoService;
import pe.gob.mininter.dirandro.service.ValorService;
import pe.gob.mininter.dirandro.vaadin.util.HarecComponent;
import pe.gob.mininter.dirandro.vaadin.util.Injector;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.TreeTable;
import com.vaadin.ui.VerticalLayout;

public class PanelMantenPais extends HarecComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private HorizontalLayout pnlPrincipal;
	@AutoGenerated
	private VerticalLayout pnlDatosEstado;
	@AutoGenerated
	private HorizontalLayout pnlEstadoBotones;
	@AutoGenerated
	private Button btnCrearEstado;
	@AutoGenerated
	private ComboBox cmbEstado;
	@AutoGenerated
	private ComboBox comboBox_1;
	@AutoGenerated
	private TextField txtNombre;
	@AutoGenerated
	private VerticalLayout pnlListadoEstado;
	@AutoGenerated
	private TreeTable filterTreeTable_2;
	@AutoGenerated
	private TextField txtFiltroCodigo;
	@AutoGenerated
	private Label lblFiltroBusqueda;
	private static final long serialVersionUID = 8017458567665421578L;
	
	private EstadoService estadoService;
	private ValorService valorService;
	private boolean flagNuevaEstado;
	
	public PanelMantenPais(List<Opcion> acciones, String height){
		super(acciones, height);
		estadoService = Injector.obtenerServicio(EstadoService.class);
		valorService = Injector.obtenerServicio(ValorService.class);
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}
	
	@Override
	public void postConstruct() {
		//TODO: Implementacion
	}
	
	private void habilitarEdicion(boolean flag){
		flagNuevaEstado = !flag;
		if(flag){
			btnCrearEstado.setCaption("Actualizar");
		}
		else{
			btnCrearEstado.setCaption("Crear");
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// pnlPrincipal
		pnlPrincipal = buildPnlPrincipal();
		mainLayout.addComponent(pnlPrincipal);
		mainLayout.setComponentAlignment(pnlPrincipal, new Alignment(20));
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlPrincipal() {
		// common part: create layout
		pnlPrincipal = new HorizontalLayout();
		pnlPrincipal.setStyleName("backColor");
		pnlPrincipal.setImmediate(false);
		pnlPrincipal.setWidth("-1px");
		pnlPrincipal.setHeight("-1px");
		pnlPrincipal.setMargin(true);
		pnlPrincipal.setSpacing(true);
		
		// pnlListadoEstado
		pnlListadoEstado = buildPnlListadoEstado();
		pnlPrincipal.addComponent(pnlListadoEstado);
		
		// pnlDatosEstado
		pnlDatosEstado = buildPnlDatosEstado();
		pnlPrincipal.addComponent(pnlDatosEstado);
		
		return pnlPrincipal;
	}

	@AutoGenerated
	private VerticalLayout buildPnlListadoEstado() {
		// common part: create layout
		pnlListadoEstado = new VerticalLayout();
		pnlListadoEstado.setImmediate(false);
		pnlListadoEstado.setWidth("-1px");
		pnlListadoEstado.setHeight("-1px");
		pnlListadoEstado.setMargin(false);
		
		// lblFiltroBusqueda
		lblFiltroBusqueda = new Label();
		lblFiltroBusqueda.setStyleName("h1");
		lblFiltroBusqueda.setImmediate(false);
		lblFiltroBusqueda.setWidth("-1px");
		lblFiltroBusqueda.setHeight("-1px");
		lblFiltroBusqueda.setValue("Fitro de Busqueda");
		pnlListadoEstado.addComponent(lblFiltroBusqueda);
		
		// txtFiltroCodigo
		txtFiltroCodigo = new TextField();
		txtFiltroCodigo.setImmediate(false);
		txtFiltroCodigo.setWidth("450px");
		txtFiltroCodigo.setHeight("-1px");
		txtFiltroCodigo.setInputPrompt("Filtro de Busqueda");
		pnlListadoEstado.addComponent(txtFiltroCodigo);
		
		// filterTreeTable_2
		filterTreeTable_2 = new TreeTable();
		filterTreeTable_2.setImmediate(false);
		filterTreeTable_2.setWidth("550px");
		filterTreeTable_2.setHeight("400px");
		pnlListadoEstado.addComponent(filterTreeTable_2);
		
		return pnlListadoEstado;
	}

	@AutoGenerated
	private VerticalLayout buildPnlDatosEstado() {
		// common part: create layout
		pnlDatosEstado = new VerticalLayout();
		pnlDatosEstado.setStyleName("h1");
		pnlDatosEstado.setCaption("Administración de Paises");
		pnlDatosEstado.setImmediate(false);
		pnlDatosEstado.setWidth("-1px");
		pnlDatosEstado.setHeight("-1px");
		pnlDatosEstado.setMargin(true);
		pnlDatosEstado.setSpacing(true);
		
		// txtNombre
		txtNombre = new TextField();
		txtNombre.setCaption("Nombre");
		txtNombre.setImmediate(false);
		txtNombre.setWidth("220px");
		txtNombre.setHeight("-1px");
		txtNombre.setRequired(true);
		txtNombre.setInputPrompt("Nombre del Estado");
		pnlDatosEstado.addComponent(txtNombre);
		
		// comboBox_1
		comboBox_1 = new ComboBox();
		comboBox_1.setCaption("Ciudad");
		comboBox_1.setImmediate(false);
		comboBox_1.setWidth("-1px");
		comboBox_1.setHeight("-1px");
		pnlDatosEstado.addComponent(comboBox_1);
		
		// cmbEstado
		cmbEstado = new ComboBox();
		cmbEstado.setCaption("Estado");
		cmbEstado.setImmediate(false);
		cmbEstado.setWidth("-1px");
		cmbEstado.setHeight("-1px");
		cmbEstado.setRequired(true);
		pnlDatosEstado.addComponent(cmbEstado);
		
		// pnlEstadoBotones
		pnlEstadoBotones = buildPnlEstadoBotones();
		pnlDatosEstado.addComponent(pnlEstadoBotones);
		pnlDatosEstado.setComponentAlignment(pnlEstadoBotones,
				new Alignment(48));
		
		return pnlDatosEstado;
	}

	@AutoGenerated
	private HorizontalLayout buildPnlEstadoBotones() {
		// common part: create layout
		pnlEstadoBotones = new HorizontalLayout();
		pnlEstadoBotones.setImmediate(false);
		pnlEstadoBotones.setWidth("-1px");
		pnlEstadoBotones.setHeight("-1px");
		pnlEstadoBotones.setMargin(false);
		pnlEstadoBotones.setSpacing(true);
		
		// btnCrearEstado
		btnCrearEstado = new Button();
		btnCrearEstado.setCaption("Crear");
		btnCrearEstado.setImmediate(true);
		btnCrearEstado.setWidth("-1px");
		btnCrearEstado.setHeight("-1px");
		pnlEstadoBotones.addComponent(btnCrearEstado);
		
		return pnlEstadoBotones;
	}
}
